# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Admin:
            algorithm: bcrypt
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_REGIONAL_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_REGIONAL_ADMIN

    providers:
        admin:
            entity:
                class: AppBundle:Admin
                property: username
        user:
            entity:
                class: AppBundle:User
                property: clid

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_unsec:
            pattern: ^/admin/login$
            security: false

        admin:
            pattern: ^/admin
            form_login:
                provider: admin
                login_path: admin_login
                check_path: admin_login_check
                username_parameter: admin_login[username]
                password_parameter: admin_login[password]
            logout:
                path: admin_logout
                target: /admin

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: user
                login_path: login
                check_path: login_check
                username_parameter: login[clid]
                use_referer: true
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/vote_settings/*, roles: ROLE_ADMIN }
        - { path: ^/admin/users/*, roles: ROLE_ADMIN }
        - { path: ^/projects/*, roles: [ROLE_USER, ROLE_ADMIN] method: [GET, POST, PUT, DELETE]}
        - { path: ^/projects/add, roles: ROLE_USER }
        - { path: ^/users, roles: ROLE_USER }
