# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
hwi_oauth:
    firewall_name: main
    resource_owners: ~
    # uncomment next lines when BankId will commited in HWIOauthBundle
#        bank_id:
#            type: bank_id
#            client_id: %client_id%
#            client_secret: %client_secret%

security:
    encoders:
        AppBundle\Entity\Admin:
            algorithm: bcrypt
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin:
            entity:
                class: AppBundle:Admin
                property: username
        user:
            entity:
                class: AppBundle:User
                property: clid

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_unsec:
            pattern: ^/admin/login$
            security: false

        admin:
            pattern: ^/admin
            form_login:
                provider: admin
                login_path: admin_login
                check_path: admin_login_check
                username_parameter: admin_login[username]
                password_parameter: admin_login[password]
            logout:
                path: admin_logout
                target: /admin

        main:
            pattern: ^/
            anonymous: ~
            oauth:
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                resource_owners:
                    bank_id: "/login/check-bank-id"

                oauth_user_provider:
                    orm:
                        class: AppBundle\Entity\User
                        properties: {'bank_id': 'clid'}
                        manager_name: default
            form_login:
                provider: user
                login_path: login
                check_path: login_check
                username_parameter: login[clid]
                use_referer: true
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/projects/, roles: ROLE_USER, method: [POST, PUT, DELETE]}
        - { path: ^/users, roles: ROLE_USER }
