# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }

    twig.project.type:
        class: AppBundle\Twig\ProjectTypeExtension
        tags:
            - { name: twig.extension }

    app.turbosms_client:
        class: SoapClient
        arguments:
            - 'http://turbosms.in.ua/api/wsdl.html'
        shared: false
        lazy: true

    app.turbosms_sender:
        class: AppBundle\Service\TurboSmsSender
        arguments:
            - '%turbosms_user%'
            - '%turbosms_pass%'
            - '%turbosms_from%'
        calls:
            - ['setLogger', ['@logger']]
            - ['setClient', ['@app.turbosms_client']]
            - ['setKernel', ['@kernel']]
        tags:
            - { name: sms_provider }

    app.alpha_sms_sender:
        class: AppBundle\Service\AlphaSmsSender
        arguments:
            - '%alpha_api_key%'
            - '%alpha_from%'
        calls:
            - ['setLogger', ['@logger']]
            - ['setKernel', ['@kernel']]
        tags:
            - { name: sms_provider }
