<?php

namespace AppBundle\Entity;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectStat()
    {
        $qb = $this->getEntityManager()->createQueryBuilder('project');
        $qb
            ->select('project')
            ->from('AppBundle:Project', 'project')
            ->addSelect('COUNT(user.id) as nMethods')
            ->leftJoin('project.likedUsers', 'user')
//            ->leftJoin('user.location', 'location')
//            ->andWhere($qb->expr()->like('location.city', $qb->expr()->literal('%ЧЕРКАС%')))
            ->groupBy('project.id')
            ->orderBy("nMethods", 'DESC')

            ->getQuery()
            ->getResult()
        ;
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function getProjectShow()
    {
        $qb = $this->getEntityManager()->createQueryBuilder('project');
        $qb
            ->select('project')
            ->from('AppBundle:Project', 'project')
            ->addSelect('COUNT(user.id) as nMethods')
            ->leftJoin('project.likedUsers', 'user')
//            ->leftJoin('user.location', 'location')
            ->andWhere('project.approved = :approved')
//            ->andWhere($qb->expr()->like('location.city', ':search'))
//            ->setParameter('search', 'ЧЕРКАС%')
            ->setParameter('approved', true)
            ->groupBy('project.id')

            ->getQuery()
            ->getResult()
        ;
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function getOneProjectShow($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('project');
        $qb
            ->select('project')
            ->from('AppBundle:Project', 'project')
            ->addSelect('COUNT(user.id) as nMethods')
            ->leftJoin('project.likedUsers', 'user')
//            ->leftJoin('user.location', 'location')
            ->andWhere('project.approved= :approved')
            ->andWhere('project.id = :id')
//            ->andWhere($qb->expr()->like('location.city', $qb->expr()->literal('%ЧЕРКАС%')))
            ->setParameter('approved', true)
            ->setParameter('id', $id)
            ->groupBy('project.id')

            ->getQuery()
            ->getResult()
        ;
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
