<?php

namespace AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCountVotedUsers()
    {
        $qb = $this->getEntityManager()->createQueryBuilder('user');
        $qb
            ->select('user')
            ->from('AppBundle:User', 'user')
            ->where('user.countVotes != :param')
            ->setParameter('param', 0)
        ;
        return count($qb->getQuery()->getArrayResult());
    }
}
