<?php

namespace AppBundle\Entity;

/**
 * VoteSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
